{{- range $repo_cred_key, $repo_cred_value := .Values.configs.credentialTemplates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-creds-{{ $repo_cred_key }}
  labels:
    argocd.argoproj.io/secret-type: repo-creds
    {{- include "argo-cd.labels" (dict "context" $) | nindent 4 }}
  {{- if $.Values.configs.annotations }}
  annotations:
  {{- range $key, $value := $.Values.configs.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  
stringData:
  {{- range $key, $value := $repo_cred_value }}
  {{ $key }}: {{ $value | toString }}
  {{- end }}
{{- end }}
